version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports: [ "6379:6379/tcp" ]
  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK