# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    
    - name: Build Docker 
      run: docker-compose build
    
    - name: Initiate Docker-Compose
      run: docker-compose up -d
    
